// src/types/app.types.ts

// Basic Point type
export type Point = {
  x: number;
  y: number;
};

// Structure for storing saved masks
export type SavedMask = {
  id: string; // Unique identifier
  name: string; // User-editable name
  maskB64Png: string; // Base64 PNG string (should include data URI prefix)
  points: Point[]; // Points used to generate this mask (empty for auto-generated)
  isActive: boolean; // Whether the mask should be displayed/used
  loadedImage: HTMLImageElement | null; // Loaded image element for drawing
  score?: number; // Optional score from backend
};

// Type for masks received from the auto-generate endpoint
export type AutoGeneratedMaskData = {
  label: string;
  score: number;
  mask_b64png: string; // Backend sends this key
};

// UI Flow Steps
export type Step = "input" | "masking" | "params" | "generating" | "result";